# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-15 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'', max_length=200, unique=True)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
